### ISSUE TITLE
Dataset file is not a gzip file 

### ISSUE THREAD

**Issue by oersoy1** [kavgan/nlp-in-practice#1] opened 2018-06-26 16:16 UTC
```bash
$ tar -zxvf reviews_data.txt.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Inspect file:

```bash
$ file reviews_data.txt.gz 
reviews_data.txt.gz: HTML document, UTF-8 Unicode text, with very long lines

$head reviews_data.txt.gz 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

```

Python gives gzip error as well 

``` python
/usr/lib/python3.5/gzip.py in _read_gzip_header(self)
    407 
    408         if magic != b'\037\213':
--> 409             raise OSError('Not a gzipped file (%r)' % magic)
    410 
    411         (method, flag,

OSError: Not a gzipped file (b'\n\n')
```

**Comment by lakeofsoft** [comment] 2019-02-08 23:10
what you get is not the original .gz file, but a github HTML page which describes it

**Comment by kavgan** [comment] 2019-02-15 19:58
Also use `gunzip`

**Comment by kavgan** [comment] 2019-02-27 21:24
Duplicate of #2

**Closed** 2020-04-28 21:27 UTC
